# Generated by Django 4.1 on 2022-08-17 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("votes", models.IntegerField(default=0)),
                (
                    "menu_monday",
                    models.TextField(blank=True, default="Menu was not published yet"),
                ),
                (
                    "menu_tuesday",
                    models.TextField(blank=True, default="Menu was not published yet"),
                ),
                (
                    "menu_wednesday",
                    models.TextField(blank=True, default="Menu was not published yet"),
                ),
                (
                    "menu_thursday",
                    models.TextField(blank=True, default="Menu was not published yet"),
                ),
                (
                    "menu_friday",
                    models.TextField(blank=True, default="Menu was not published yet"),
                ),
                (
                    "menu_saturday",
                    models.TextField(blank=True, default="Menu was not published yet"),
                ),
                (
                    "menu_sunday",
                    models.TextField(blank=True, default="Menu was not published yet"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote",
                        to="restaurant.restaurant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_vote",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
