# Generated by Django 4.1 on 2022-08-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vote",
            name="user",
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="menu_friday",
            field=models.TextField(blank=True, default="No info"),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="menu_monday",
            field=models.TextField(blank=True, default="No info"),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="menu_saturday",
            field=models.TextField(blank=True, default="No info"),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="menu_sunday",
            field=models.TextField(blank=True, default="No info"),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="menu_thursday",
            field=models.TextField(blank=True, default="No info"),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="menu_tuesday",
            field=models.TextField(blank=True, default="No info"),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="menu_wednesday",
            field=models.TextField(blank=True, default="No info"),
        ),
    ]
