# Generated by Django 4.1 on 2022-08-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_remove_vote_user_alter_restaurant_menu_friday_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="menu_friday",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="menu_monday",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="menu_saturday",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="menu_sunday",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="menu_thursday",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="menu_tuesday",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="menu_wednesday",
            field=models.TextField(blank=True),
        ),
    ]
